artifact_uri: file:///home/mat/PycharmProjects/ml4grownups/src/mlruns/0/3dc804b2ad6b4a5db12162b852e03e25/artifacts
end_time: 1642414276211
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 3dc804b2ad6b4a5db12162b852e03e25
run_uuid: 3dc804b2ad6b4a5db12162b852e03e25
source_name: ''
source_type: 4
source_version: ''
start_time: 1642414276084
status: 3
tags: []
user_id: mat
